name: savejson_buildinginfos
description: Creating required BuildingInfo json file by reading the svg file placed in Assets folder.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  xml: ^6.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
