name: savejson_buildinginfos
description: Creating required BuildingInfo json file by reading the svg file placed in Assets folder.
version: 1.0.0
publish_to: none
repository: https://github.com/binSallushan/CommunityApp

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  xml: ^6.5.0
  models:
    path: C:/Users/muavi/source/repos/AskanCommunityApp/models
              
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
