name: models
description: A package containing shared models for building information, coordinates, and sides. Used in AskanCommunityApp
version: 1.0.0
environment:
  sdk: ">=2.19.0 <4.0.0" # Update based on your Dart version.
